import { StyleSheet } from 'react-native';


const styles = StyleSheet.create({
  imageIcon: {
    position: 'absolute',
    top: 362,
    left: 116,
    borderRadius: 22,
    width: 111,
    height: 150,
    resizeMode: 'cover',
  },
  imageIcon1: {
    position: 'absolute',
    top: 0,
    left: 0,
    borderRadius: 18,
    width: 111,
    height: 154,
    resizeMode: 'cover',
  },
  imageIcon2: {
    position: 'absolute',
    top: 159,
    left: 0,
    borderRadius: 18,
    width: 111,
    height: 147,
    resizeMode: 'cover',
  },
  imageIcon3: {
    position: 'absolute',
    top: 311,
    left: 0,
    borderRadius: 18,
    width: 111,
    height: 135,
    resizeMode: 'cover',
  },
  imageIcon4: {
    position: 'absolute',
    top: 0,
    left: 116,
    borderRadius: 18,
    width: 111,
    height: 175,
    resizeMode: 'cover',
  },
  imageIcon5: {
    position: 'absolute',
    top: 182,
    left: 116,
    borderRadius: 18,
    width: 111,
    height: 175,
    resizeMode: 'cover',
  },
  imageIcon6: {
    position: 'absolute',
    top: 0,
    left: 232,
    borderRadius: 18,
    width: 111,
    height: 147,
    resizeMode: 'cover',
  },
  imageIcon7: {
    position: 'absolute',
    top: 154,
    left: 232,
    borderRadius: 18,
    width: 111,
    height: 131,
    resizeMode: 'cover',
  },
  imageIcon8: {
    position: 'absolute',
    top: 292,
    left: 232,
    borderRadius: 18,
    width: 111,
    height: 163,
    resizeMode: 'cover',
  },
  imageParent: {
    position: 'absolute',
    top: 60,
    left: 25,
    width: 343,
    height: 537,
  },
  overlay: {
    position: 'absolute',
    bottom: 0,
    left: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
    width: 359,
    height: 283,
  },
  image: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 375,
    height: 568,
    overflow: 'hidden',
  },
  line: {
    position: 'absolute',
    bottom: 8,
    left: '50%',
    marginLeft: -67.5,
    borderRadius: 100,
    backgroundColor: '#000',
    width: 135,
    height: 5,
  },
  indicator: {
    position: 'absolute',
    width: '100%',
    height: 33,
    bottom: 0,
  },
  border: {
    position: 'absolute',
    top: 0,
    right: 2.3,
    borderRadius: 2.67,
    borderWidth: 1,
    borderColor: 'rgba(60, 60, 67, 0.6)',
    width: 22,
    height: 11.3,
    opacity: 0.35,
  },
  capIcon: {
    position: 'absolute',
    top: 3.67,
    right: 0,
    width: 1.3,
    height: 4,
    opacity: 0.4,
  },
  capacity: {
    position: 'absolute',
    top: 2,
    right: 4.3,
    borderRadius: 1.33,
    backgroundColor: '#000',
    width: 18,
    height: 7.3,
  },
  battery: {
    position: 'absolute',
    top: 0,
    right: 0.07,
    width: 24.3,
    height: 11.3,
  },
  wifiIcon: {
    position: 'relative',
    width: 15.3,
    height: 11,
  },
  cellularConnectionIcon: {
    position: 'relative',
    width: 17,
    height: 10.7,
  },
  group: {
    position: 'absolute',
    top: 17.33,
    right: 14.3,
    width: 66.7,
    height: 11.3,
  },
  span: {
    letterSpacing: -0.28,
  },
  time: {
    position: 'absolute',
    width: '100%',
    top: '50%',
    left: 0,
    lineHeight: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  starus: {
    position: 'absolute',
    height: '47.73%',
    top: '27.27%',
    bottom: '25%',
    left: 21,
    width: 54,
  },
  systemBar: {
    position: 'absolute',
    width: '100%',
    top: 0,
    height: 44,
  },
  logoIcon: {
    width: 96,
    height: 96,
    position: 'relative',
    overflow: 'hidden',
  },
  welcomeToPinterest: {
    width: '100%',
  position: 'relative', // Bạn có thể sử dụng 'relative' hoặc 'absolute' tùy vào nhu cầu.
  fontSize: 28,
  display: 'flex', // Trong React Native không có 'inline-block', bạn có thể dùng 'flex'.
  fontFamily: 'SF Pro', // Phải đảm bảo rằng font này được thêm vào trong dự án React Native.
  color: '#191919',
  textAlign: 'center',
  },
  logo: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 9,
    gap: 12,
  },
  button: {
    position: 'relative',
    letterSpacing: -0.02,
    lineHeight: 20,
    fontWeight: '600',
  },
  buttonBase: {
    flex: 1,
    borderRadius: 100,
    backgroundColor: '#e60023',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  buttons: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  buttonBase1: {
    flex: 1,
    borderRadius: 100,
    backgroundColor: '#f1f1f1',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  buttons1: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    color: '#191919',
  },
  buttonGroup: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    gap: 10,
    fontSize: 16,
    color: '#fff',
  },
  byContinuingYou: {
    position: 'relative',
    lineHeight: 14,
  },
  termsOfService: {
    position: 'relative',
    lineHeight: 14,
    fontWeight: '600',
  },
  byContinuingYouAgreeToPiParent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 2,
  },
  terms: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    gap: 1,
    textAlign: 'left',
    fontSize: 12,
  },
  content: {
    position: 'absolute',
    width: '100%',
    right: 0,
    bottom: 33,
    left: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 22,
    fontSize: 28,
    color: '#191919',
  },
  signUp1: {
    width: '100%',
    position: 'relative',
    backgroundColor: '#fff',
    height: 812,
    overflow: 'hidden',
    textAlign: 'center',
    fontSize: 14,
    color: '#000',
  },
});



export default styles;
